### ISSUE TITLE
[ResizeBox/伸缩框] 功能需求，希望增加这个组件！

### ISSUE THREAD

**Issue by kwooshung** [Tencent/tdesign#739]
### 这个功能解决了什么问题

这个功能我认为也是非常常用的，不仅可以分割面板！
例如：可以轻松做到输入框往下拉，即可修改输入框高度。十分灵活的一个功能。
据我所知目前仅 Arco Design 有这个功能。

### 你建议的方案是什么

- Arco Design：https://arco.design/react/components/resize-box
- 如果打算实现这个组件，这里有我之前给Arco Design 提交的Issue：https://github.com/arco-design/arco-design/issues/1016 避免出现同样的问题。
```[tasklist]
### Tasks
- [ ] https://github.com/Tencent/tdesign-react/issues/2309
- [ ] https://github.com/Tencent/tdesign-react/issues/2310
- [ ] https://github.com/Tencent/tdesign-react/issues/2311
- [ ] https://github.com/Tencent/tdesign-react/issues/2312
- [ ] https://github.com/Tencent/tdesign/issues/732
- [ ] https://github.com/Tencent/tdesign/issues/738
```
